# -*- coding: utf-8 -*-
"""Predictive_analytic_new.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rIRhJMVsd9CTIe6yKKKjFyzod1GKmhJj

Nama : Putu Padmanaba

Email : naba17092004@gmail.com

Domisili : Denpasar, Bali

Beasiswa : IDcamp Indosat

#Data Collection

Dataset ini diambil dari: https://www.kaggle.com/datasets/mssmartypants/water-quality
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import zipfile

"""####Instal Package Kaggle"""

! pip install -q kaggle

"""####Upload Json Profile Kaggle"""

from google.colab import files

files.upload()

"""####Membuat direktori dan mengatur izin agar bisa memasukan JSON Kaggle"""

! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

"""####Mendownload Dataset"""

!kaggle datasets download -d mssmartypants/water-quality

"""####Ekstrak Zipfile"""

local_zip = '/content/water-quality.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/content')
zip_ref.close()

"""####Memuat dataset ke dalam Pandas Dataframe"""

df = pd.read_csv("waterQuality1.csv")
df.head()

"""#Data Understanding

####Mengecek informasi dari dataset
"""

df.shape

df.info()

df['ammonia'].head()

"""#### Mengubah kolom "ammonia" menjadi tipe float64"""

df['ammonia'] = pd.to_numeric(df['ammonia'], errors='coerce')

"""####Mengecek missing value"""

df.isnull().sum()

"""####Mengecek statistik dari data"""

df.describe()

"""#### Mengecek keseimbangan dataset berdasarkan target class"""

plt.figure(figsize=(10,6))
sns.countplot(df,x="is_safe")
plt.title("Safe drinking water ratio ", size =17)

"""####Melihat korelasi antar features"""

Corrmat = df.corr()
plt.subplots(figsize=(11,11))
sns.heatmap(Corrmat, cmap="YlGnBu", annot=True, fmt='.2f')
plt.show()

"""#Data preparation

####Menangani missing value
"""

df = df.dropna()

df.head()

df.isnull().sum()

"""#### Menyeimbangkan dataset dengan metode downsampling"""

from sklearn.utils import resample

jumlah = df[df['is_safe'] == '1'].count()
jumlah

sample_0 = df[df['is_safe']=='0']
sample_1 = df[df['is_safe']=='1']

downsample_0 = resample(
    sample_0,
    replace = True,
    n_samples = 912,
    random_state=42
)
downsample_1 = resample(
    sample_1,
    replace = True,
    n_samples = 912,
    random_state=42
)

df_downsample = pd.concat([downsample_0,downsample_1])
df_downsample.shape

"""####Membagi dataset menjadi training set dan test set"""

from sklearn.model_selection import train_test_split

X = df_downsample.drop(['is_safe'],axis=1)
y = df_downsample['is_safe']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25,random_state=1)

#mengecek jumlah dataset
print(X_train.shape)
print(X_test.shape)

"""####Standarisasi"""

from sklearn.preprocessing import StandardScaler

features = ['aluminium', 'ammonia', 'arsenic', 'barium', 'cadmium', 'chloramine', 'chromium', 'copper', 'flouride', 'bacteria', 'viruses', 'lead', 'nitrates', 'nitrites', 'mercury', 'perchlorate', 'radium', 'selenium', 'silver', 'uranium']
scaler = StandardScaler()
scaler.fit(X_train.loc[:, features])
X_train_scaled = scaler.transform(X_train.loc[:, features])
X_train.loc[:, features] = X_train_scaled
X_train.head()

X_train.describe().round(3)

"""#Modeling

####Normalisasi dataset test
"""

from sklearn.preprocessing import StandardScaler

features = ['aluminium', 'ammonia', 'arsenic', 'barium', 'cadmium', 'chloramine', 'chromium', 'copper', 'flouride', 'bacteria', 'viruses', 'lead', 'nitrates', 'nitrites', 'mercury', 'perchlorate', 'radium', 'selenium', 'silver', 'uranium']
scaler = StandardScaler()
scaler.fit(X_test.loc[:, features])
X_test_scaled = scaler.transform(X_test.loc[:, features])
X_test.loc[:, features] = X_test_scaled
X_test.head()

"""####Liblary untuk metrix evaluasi model"""

from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score

"""####Dataframe untuk analisis akurasi model"""

models = pd.DataFrame(index=['accuracy', 'precision', 'recall', 'f1_score'],
                      columns=['KNN', 'SVM', 'Randomforest'])

"""####KNN"""

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=25)
knn.fit(X_train,y_train)

"""####SVC"""

from sklearn.svm import SVC

svc = SVC(C=5)
svc.fit(X_train,y_train)

"""####Random Forest"""

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=110,max_depth=16, random_state=123, n_jobs=1)
rf.fit(X_train,y_train)

"""#Evaluasi model

####Menghitung matrix evaluasi model
"""

# KNN
models.loc['accuracy', 'KNN'] = accuracy_score(y_pred=knn.predict(X_test),y_true=y_test)
models.loc['recall', 'KNN'] = recall_score(y_pred=knn.predict(X_test),y_true=y_test,pos_label='1')
models.loc['precision', 'KNN'] = precision_score(y_pred=knn.predict(X_test),y_true=y_test,pos_label='1')
models.loc['f1_score', 'KNN'] = f1_score(y_pred=knn.predict(X_test),y_true=y_test,pos_label='1')
# SVC
models.loc['accuracy', 'SVM'] = accuracy_score(y_pred=svc.predict(X_test),y_true=y_test)
models.loc['recall', 'SVM'] = recall_score(y_pred=svc.predict(X_test),y_true=y_test,pos_label='1')
models.loc['precision', 'SVM'] = precision_score(y_pred=svc.predict(X_test),y_true=y_test,pos_label='1')
models.loc['f1_score', 'SVM'] = f1_score(y_pred=svc.predict(X_test),y_true=y_test,pos_label='1')
# RandomForest
models.loc['accuracy', 'Randomforest'] = accuracy_score(y_pred=rf.predict(X_test),y_true=y_test)
models.loc['recall', 'Randomforest'] = recall_score(y_pred=rf.predict(X_test),y_true=y_test,pos_label='1')
models.loc['precision', 'Randomforest'] = precision_score(y_pred=rf.predict(X_test),y_true=y_test,pos_label='1')
models.loc['f1_score', 'Randomforest'] = f1_score(y_pred=rf.predict(X_test),y_true=y_test,pos_label='1')

"""####Menanpilkan hasil evaluasi model"""

models